name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  packages: read
  id-token: write

jobs:
  build:
    name: Build and Deploy via ${{ matrix.name }}
    if: |
      (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[ci]'))
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Mkdocs to Github Pages
            image: ghcr.io/raineblog/mkdocs-docker:latest
            cache: gh-mkdocs
            pwd: |
              mkdocs-build
              mkdocs-gulp
            url: https://raineblog.dpdns.org/whk/
            branch: gh-pages
            type: normal
            dir: ./site
          - name: Mkdocs to Cloudflare Pages
            image: ghcr.io/raineblog/mkdocs-docker:latest
            cache: cf-mkdocs
            pwd: |
              mkdocs-build
              mkdocs-gulp
            url: https://raineblog-whk.pages.dev/
            branch: cloudflare-pages
            type: normal
            dir: ./site

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          submodules: "true"
          fetch-depth: 0
          fetch-tags: false

      - name: Cache
        uses: actions/cache@v5
        with:
          path: .cache
          key: ${{ runner.os }}-${{ matrix.cache }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.cache }}-

      - name: Build Static Site
        run: ${{ matrix.pwd }}
        env:
          site_url: ${{ matrix.url }}
          build_type: ${{ matrix.type }}

      - name: Push to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: ${{ matrix.branch }}
          publish_dir: ${{ matrix.dir }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          full_commit_message: "Deploying to gh-pages from ${{ github.sha }}"
