name: SEO Push

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  seo-push:
    name: SEO Push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/raineblog/mkdocs-docker:latest
    steps:
      - name: SEO Push
        env:
          SITE_HOST: "raineblog.dpdns.org"
          SITE_BASE: "https://raineblog.dpdns.org"
          SITE_NAME: "RainPPR's WHK Wiki"
          SITE_PROJECT: "whk"
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run: mkdocs-seo
